//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveLisp.Core.Types {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MathResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MathResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveLisp.Types.MathResources", typeof(MathResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to big integer won&apos;t fit into byte.
        /// </summary>
        public static string BigIntWontFitByte {
            get {
                return ResourceManager.GetString("BigIntWontFitByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to big integer won&apos;t fit into char.
        /// </summary>
        public static string BigIntWontFitChar {
            get {
                return ResourceManager.GetString("BigIntWontFitChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to big integer won&apos;t fit into decimal.
        /// </summary>
        public static string BigIntWontFitDecimal {
            get {
                return ResourceManager.GetString("BigIntWontFitDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to big integer won&apos;t fit into int.
        /// </summary>
        public static string BigIntWontFitInt {
            get {
                return ResourceManager.GetString("BigIntWontFitInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to big integer won&apos;t fit into long.
        /// </summary>
        public static string BigIntWontFitLong {
            get {
                return ResourceManager.GetString("BigIntWontFitLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to big integer won&apos;t fit into sbyte.
        /// </summary>
        public static string BigIntWontFitSByte {
            get {
                return ResourceManager.GetString("BigIntWontFitSByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to big integer won&apos;t fit into short.
        /// </summary>
        public static string BigIntWontFitShort {
            get {
                return ResourceManager.GetString("BigIntWontFitShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to big integer won&apos;t fit into uint.
        /// </summary>
        public static string BigIntWontFitUInt {
            get {
                return ResourceManager.GetString("BigIntWontFitUInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to big integer won&apos;t fit into ulong.
        /// </summary>
        public static string BigIntWontFitULong {
            get {
                return ResourceManager.GetString("BigIntWontFitULong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to big integer won&apos;t fit into ushort.
        /// </summary>
        public static string BigIntWontFitUShort {
            get {
                return ResourceManager.GetString("BigIntWontFitUShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complex division by zero.
        /// </summary>
        public static string ComplexDivizionByZero {
            get {
                return ResourceManager.GetString("ComplexDivizionByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected integer.
        /// </summary>
        public static string ExpectedInteger {
            get {
                return ResourceManager.GetString("ExpectedInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to format not implemented.
        /// </summary>
        public static string FormatNotImplemented {
            get {
                return ResourceManager.GetString("FormatNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid argument.
        /// </summary>
        public static string InvalidArgument {
            get {
                return ResourceManager.GetString("InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to power must be &gt;= 0.
        /// </summary>
        public static string NonNegativePower {
            get {
                return ResourceManager.GetString("NonNegativePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we.
        /// </summary>
        public static string qwe {
            get {
                return ResourceManager.GetString("qwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radix must be &lt;= 36.
        /// </summary>
        public static string RadixGreaterThan36 {
            get {
                return ResourceManager.GetString("RadixGreaterThan36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radix must be &gt;= 2.
        /// </summary>
        public static string RadixLessThan2 {
            get {
                return ResourceManager.GetString("RadixLessThan2", resourceCulture);
            }
        }
    }
}
